/**
 * Transforms the given text generated by perplexity.ai into a text which can be meaningfully transformed to audio
 * speaking out the text by Amazon Alexa.
 * @param perplexity text generated by perplexity.ai containing substrings to suited for text to audio synthesis
 * @returns transformed text as input for audio generation by Alexa
 */
export function transformPerplexityOutputForAlexa(perplexity: string): string {
        let transformed = perplexity;
        
        // Check if text originally ended with reference with space before it
        const endsWithSpacedReference = /\s+\[\d+\]$/.test(transformed);
        
        // Remove references like [1], [2], etc.
        transformed = transformed.replace(/\s*\[\d+\]/g, '');
        
        // Remove bold text markings **text** everywhere
        transformed = transformed.replace(/\*\*(.*?)\*\*/g, '$1');
        
        // Remove headline markings (# ## ###)
        transformed = transformed.replace(/#+\s*/g, '');
        
        // Clean up extra spaces
        transformed = transformed.replace(/\s+/g, ' ').trim();
        
        // Add period only if text ended with spaced reference and doesn't end with punctuation
        if (endsWithSpacedReference && transformed && !transformed.match(/[.!?]$/)) {
            transformed += '.';
        }
        
        return transformed;
}